###########
# site.title

title:    'Spark Minimal Theme'
subtitle: 'A simple spark theme'

destination: public
source: src

markdown: kramdown

sass:
  sass_dir: css
  style:    compressed

exclude: ['node_modules']
