###########
# site.title

title:    'Spark Minimal Theme'
subtitle: 'A simple spark theme'


nav:
- { title: 'Welcome',              href: '/' }
- { title: 'About Us',             href: '/about.html' }
- { title: 'Contact',           href: '/contact.html' }
#- { title: 'About',                href: 'https://github.com/henrythemes/jekyll-starter-theme-v2' }

markdown: kramdown

sass:
  sass_dir: css
  style:    compressed

exclude:
- README.md